[package]
name = "orx-criterion"
version = "0.1.0"
edition = "2024"
publish = ["artifactory"]

[dependencies]
cli-table = { version = "0.5.0" }
colorize = { version = "0.1.0" }
criterion = { version = "0.8.2" }

[[bench]]
name = "my_test_bench"
harness = false
