[package]
name = "orx-criterion"
version = "0.1.0"
edition = "2024"
publish = ["artifactory"]

[dependencies]
criterion = { version = "0.8.2", registry = "artifactory" }

[[bench]]
name = "my_test_bench"
harness = false
