[package]
name = "orx-criterion"
version = "0.1.0"
edition = "2024"
publish = ["artifactory"]

[dependencies]
cli-table = { version = "0.5.0" }
criterion = { version = "0.8.2" }
csv = { version = "1.4.0" }

[dev-dependencies]
orx-parallel = { version = "3.4.0" }

[[bench]]
name = "my_test_bench"
harness = false
